name: discord
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cached_annotation: ^1.6.0
  crypt: ^4.3.0
  mongo_dart: ^0.9.1
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
